feat: getattr and iter dunders
ApeWorX/ape-tokens pull request #42
Opened 2024-03-11 22:04 UTC by BobTheBuidler

### What I did

added getattr and iter dundermethods to the token manager

fixes: #

### How I did it
n/a

### How to verify it
try to iter and getattr

### Checklist

- [ ] Passes all linting checks (pre-commit and CI jobs)
- [ ] New test cases have been added and are passing
- [ ] Documentation has been updated
- [ ] PR title follows [Conventional Commit](https://www.conventionalcommits.org/en/v1.0.0/) standard (will be automatically included in the changelog)

2024-05-20 16:54 UTC, antazoey commented on ape_tokens/managers.py
> +        for token in self._manager.get_tokens(chainid=self.provider.chain_id):
it looks like this should be `chain_id`: https://github.com/ApeWorX/py-tokenlists/blob/main/tokenlists/manager.py#L100

2024-05-20 16:58 UTC, antazoey commented on ape_tokens/managers.py
> +    def __iter__(self) -> Iterator[ContractInstance]:
I tried running:

```python
[x for x in tokens]
```

but got this:

```python
KeyError: "Symbol 'AZRX' is not a known token symbol"

In [2]: [x for x in tokens]
```

kinda weird.  I do have multiple token lists installed though.

2024-05-20 17:03 UTC, antazoey commented on ape_tokens/managers.py
> +    def __iter__(self) -> Iterator[ContractInstance]:
I wonder if something like:

```python
 def __iter__(self) -> Iterator[ContractInstance]:
        yielded = set()
        for token in self._manager.get_tokens(chain_id=self.provider.chain_id):
            if token.symbol in yielded:
                # Handle multiple lists.
                continue

            try:
                yield self[token.symbol]
            except KeyError:
                # Perhaps in another list?
                continue

            yielded.add(token.symbol)
```

would work for this situation.
I tried it again, except changed it to:

```python
for x in tokens:
   ...:     print(x)
```

I see the first like hundred get printed out super fast, and then it suddenly is very slow at outputting them.
hmmmmm

2024-05-23 00:53 UTC, BobTheBuidler commented on ape_tokens/managers.py
> +    def __iter__(self) -> Iterator[ContractInstance]:
is it possible the slowness is from downloading the last of the tokenlists? Looking at this code again I'm not sure where else a slowdown might come from.

2024-05-23 22:35 UTC, antazoey requested changes

2024-05-23 22:35 UTC, antazoey commented on ape_tokens/managers.py
>              raise KeyError(f"Symbol '{symbol}' is not a known token symbol") from err
```suggestion
            raise KeyError(f"Symbol '{symbol}' is not a known token symbol")
```

`from err` makes it crash out because err is not defined.

2024-05-23 22:35 UTC, antazoey commented on ape_tokens/managers.py
> +        for token in self._manager.get_tokens(chain_id=self.provider.chain_id):
I am getting the `KeyError` here when doing `[x for x in token`]

```
File ~/PycharmProjects/ape-tokens/ape_tokens/managers.py:137, in TokenManager.__getitem__(self, symbol)
    134         continue
    136 if token_info is None:
--> 137     raise KeyError(f"Symbol '{symbol}' is not a known token symbol")
    139 checksummed_address = to_checksum_address(token_info.address)
    140 try:

KeyError: "Symbol 'GETH' is not a known token symbol"

In [2]: 
```

2024-05-23 22:46 UTC, antazoey commented on ape_tokens/managers.py
> +            except ValueError:
else `err` is not defined below:

```suggestion
            except ValueError as err:
```

2025-02-27 03:19 UTC, fubuloubu commented
Added `__iter__` (and `__len__`) via https://github.com/ApeWorX/ape-tokens/pull/55

2025-05-05 20:25 UTC, fubuloubu commented
closed in favor of #55 

thank you for your suggestions!

2025-05-05 20:25 UTC, closed without merging